import {
  LaptopOutlined,
  NotificationOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { DownOutlined } from "@ant-design/icons";
import { MenuProps, Space } from "antd";
import { Layout as AntdLayout, Dropdown, Menu } from "antd";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

import styles from "./index.module.css";

const { Header, Content, Sider } = AntdLayout;

const items1: MenuProps["items"] = ["1", "2", "3"].map((key) => ({
  key,
  label: `nav ${key}`,
}));

const items2: MenuProps["items"] = [
  UserOutlined,
  LaptopOutlined,
  NotificationOutlined,
].map((icon, index) => {
  const key = String(index + 1);

  return {
    key: `sub${key}`,
    icon: React.createElement(icon),
    label: `subnav ${key}`,

    children: new Array(4).fill(null).map((_, j) => {
      const subKey = index * 4 + j + 1;
      return {
        key: subKey,
        label: `option${subKey}`,
      };
    }),
  };
});

const ITEMS = [
  {
    // icon: React.createElement(icon),
    label: "公告管理",
    key: "announcement",

    children: [
      { label: "公告列表", key: "/announcement" },
      { label: "公告添加", key: "/announcement/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "学生管理",
    key: "student",

    children: [
      { label: "学生列表", key: "/student" },
      { label: "学生添加", key: "/student/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "成绩管理",
    key: "grade",

    children: [
      { label: "用户列表", key: "/grade" },
      { label: "用户添加", key: "/grade/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "老师管理",
    key: "teacher",

    children: [
      { label: "分类列表", key: "/teacher" },
      { label: "分类添加", key: "/teacher/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "用户管理",
    key: "user",

    children: [
      { label: "用户列表", key: "/user" },
      { label: "用户添加", key: "/user/add" },
    ],
  },
 
];

const USER_ITEMS: MenuProps["items"] = [
  {
    label: "用户中心",
    key: "1",
  },
  {
    label: "登出",
    key: "2",
  },
];

export function Layout({ children }:any) {
  const router = useRouter();
  const handleMenuClick = ({ key }:any) => {
    router.push(key);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header className={styles.header}>
            <Image
              src="/graduate.png"
              width={40}
              height={40}
              alt="logo"
              className={styles.logo}
            />
            学生管理系统
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS }} className={styles.dropDown}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    <span>用户名</span>
                    <DownOutlined rev={undefined} />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout className={styles.sectionInner}>
            <Sider width={200}>
              <Menu
                mode="inline"
                defaultSelectedKeys={["/student"]}
                defaultOpenKeys={["student"]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <AntdLayout className={styles.sectionContent}>
              <Content className={styles.content} style={{overflow:"hidden"}}>{children}</Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
}
